:!last-update-label:
:compat-mode!:
Minimum Viable Secure Product
=============================
MVSP Working Group <wg@mvsp.dev>
v0.9.3, 2021-09-06
+++
<div class="noprint">
  <button type="button" onclick="toPrintTheChecklist(event)">Print checklist</button>
  <button type="button" onclick="onlineChecklist()">Complete checklist online</button>
  <button type="button" onclick="generateIframe(event)">Generate Iframe</button>
</div>
<a href="" target="_blank" class="generatedLink">
  <img class="h-8 w-auto sm:h-10" src="/images/logo.svg" alt="">
</a>
+++

Minimum Viable Secure Product is a minimalistic security checklist for B2B software and business process outsourcing suppliers. 

Designed with simplicity in mind, the checklist contains only those controls that must be implemented to ensure minimally viable security posture of a product.

We recommend that all companies building B2B software or otherwise handling sensitive information under its broadest definition implement at least the following controls, and are strongly encouraged to go well beyond them in their security programs.

[cols="2,3a,1 ,1",stripes=none]
|===
1+| Company
3+| +++<textarea class="notes" name="company" onkeydown="dynamicHeight(event)" rows="1" cols="75" disabled> +++
1+| Product
3+| +++<textarea class="notes" name="product" onkeydown="dynamicHeight(event)" rows="1" cols="75" disabled> +++

4+<h| 1 Business controls
h| Control
h| Description
h| Response
h| Notes

| 1.1 Vulnerability reports
| * Publish the point of contact for security reports on your website
* Respond to security reports within a reasonable time frame
| +++
<input type="radio" id="VulnerabilityTrue" name="Vulnerability" value="True" disabled>
<label for="VulnerabilityTrue">True</label><br>
<input type="radio" id="VulnerabilityFalse" name="Vulnerability" value="False" disabled>
<label for="VulnerabilityFalse">False</label><br>
+++
| +++ <textarea class="notes" name="Vulnerability" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 1.2 Customer testing
| * On request, enable your customers or their delegates to test the security of your application
* Test on a non-production environment if it closely resembles the production environment in functionality
* Ensure non-production environments do not contain production data
| +++
<input type="radio" id="customerTestingTrue" name="customerTesting" value="True" disabled>
<label for="customerTestingTrue">True</label><br>
<input type="radio" id="customerTestingFalse" name="customerTesting" value="False" disabled>
<label for="customerTestingFalse">False</label><br>
+++
| +++ <textarea class="notes" name="customerTesting" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 1.3 Self-assessment
| Perform annual (at a minimum) security self-assessments using this document
| +++
<input type="radio" id="self-assessmentsTrue" name="self-assessments" value="True" disabled>
<label for="self-assessmentsTrue">True</label><br>
<input type="radio" id="self-assessmentsFalse" name="self-assessments" value="False" disabled>
<label for="self-assessmentsFalse">False</label><br>
+++
| +++ <textarea class="notes" name="self-assessments" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 1.4 External testing
| Contract a security vendor to perform annual, comprehensive penetration tests on your systems
| +++
<input type="radio" id="externalTestingTrue" name="externalTesting" value="True" disabled>
<label for="externalTestingTrue">True</label><br>
<input type="radio" id="externalTestingFalse" name="externalTesting" value="False" disabled>
<label for="externalTestingFalse">False</label><br>
+++
| +++ <textarea class="notes" name="externalTesting" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++


| 1.5 Training
| Implement role-specific security training for your personnel that is relevant to their business function
| +++
<input type="radio" id="trainingTrue" name="training" value="True" disabled>
<label for="trainingTrue">True</label><br>
<input type="radio" id="trainingFalse" name="training" value="False" disabled>
<label for="trainingFalse">False</label><br>
+++
| +++ <textarea class="notes" name="training" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 1.6 Compliance
| * Comply with all industry security standards relevant to your business such as PCI DSS, HITRUST, ISO27001, and SSAE 18
* Comply with local laws and regulations in jurisdictions applicable to your company and your customers, such as GDPR, Binding Corporate Rules, and Standard Contractual Clauses
| +++
<input type="radio" id="complianceTrue" name="compliance" value="True" disabled>
<label for="complianceTrue">True</label><br>
<input type="radio" id="complianceFalse" name="compliance" value="False" disabled>
<label for="complianceFalse">False</label><br>
+++
| +++ <textarea class="notes" name="compliance" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 1.7 Incident handling
| * Notify your customers about a breach without undue delay, no later than 72 hours upon discovery
  * Include the following information in the notification:
  ** Relevant point of contact
  ** Preliminary technical analysis of the breach
  ** Remediation plan with reasonable timelines
  | +++
<input type="radio" id="incidentHandlingTrue" name="incidentHandling" value="True" disabled>
<label for="incidentHandlingTrue">True</label><br>
<input type="radio" id="incidentHandlingFalse" name="incidentHandling" value="False" disabled>
<label for="incidentHandlingFalse">False</label><br>
+++
| +++ <textarea class="notes" name="incidentHandling" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++
  
| 1.8 Data sanitization
| Ensure media sanitization processes based on NIST SP 800-88 or equivalent are implemented
| +++
<input type="radio" id="dataSanitizationTrue" name="dataSanitization" value="True" disabled>
<label for="dataSanitizationTrue">True</label><br>
<input type="radio" id="dataSanitizationFalse" name="dataSanitization" value="False" disabled>
<label for="dataSanitizationFalse">False</label><br>
+++
| +++ <textarea class="notes" name="dataSanitization" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

4+<h| 2 Application design controls
h| Control
h| Description
h| Response
h| Notes

| 2.1 Single Sign-On
| Implement single sign-on using modern and industry standard protocols
| +++
<input type="radio" id="singleSign-OnTrue" name="singleSign-On" value="True" disabled>
<label for="singleSign-OnTrue">True</label><br>
<input type="radio" id="singleSign-OnFalse" name="singleSign-On" value="False" disabled>
<label for="singleSign-OnFalse">False</label><br>
+++
| +++ <textarea class="notes" name="singleSign-On" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.2 HTTPS-only
| * Redirect traffic from HTTP protocol (port 80) to HTTPS (port 443)
  
  This does not apply to secure protocols designed to run on top of unencrypted connections, such as OCSP

  * Produce a clear scan using a widely adopted TLS scanning tool
  * Include the Strict-Transport-Security header on all pages with the `includeSubdomains` directive
  | +++
<input type="radio" id="HTTPS-onlyTrue" name="HTTPS-only" value="True" disabled>
<label for="HTTPS-onlyTrue">True</label><br>
<input type="radio" id="HTTPS-onlyFalse" name="HTTPS-only" value="False" disabled>
<label for="HTTPS-onlyFalse">False</label><br>
+++
| +++ <textarea class="notes" name="HTTPS-only" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.3 Content Security Policy
| Set a minimally permissive Content Security Policy
| +++
<input type="radio" id="contentSecurityTrue" name="contentSecurity" value="True" disabled>
<label for="contentSecurityTrue">True</label><br>
<input type="radio" id="contentSecurityFalse" name="contentSecurity" value="False" disabled>
<label for="contentSecurityFalse">False</label><br>
+++
| +++ <textarea class="notes" name="contentSecurity" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.4 Password policy
| If password authentication is used in addition to single sign-on:
  
  * Do not limit the permitted characters that can be used
  * Do not limit the length of the password to anything below 64 characters
  * Do not use secret questions as a sole password reset requirement
  * Require email verification of a password change request
  * Require the current password in addition to the new password during password change
  * Verify newly created passwords against common passwords lists or leaked passwords databases
  * Check existing user passwords for compromise regularly
  * Store passwords in a hashed and salted format using a memory-hard or CPU-hard one-way hash function
  * Enforce appropriate account lockout and brute-force protection on account access
  | +++
<input type="radio" id="passwordPolicyTrue" name="passwordPolicy" value="True" disabled>
<label for="passwordPolicyTrue">True</label><br>
<input type="radio" id="passwordPolicyFalse" name="passwordPolicy" value="False" disabled>
<label for="passwordPolicyFalse">False</label><br>
+++
| +++ <textarea class="notes" name="passwordPolicy" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.5 Security libraries
| Use frameworks, template languages, or libraries that systemically address implementation weaknesses by escaping the outputs and sanitizing the inputs. 

  Example: ORM for database access, UI framework for rendering DOM
| +++
<input type="radio" id="securityLibrariesTrue" name="securityLibraries" value="True" disabled>
<label for="securityLibrariesTrue">True</label><br>
<input type="radio" id="securityLibrariesFalse" name="securityLibraries" value="False" disabled>
<label for="securityLibrariesFalse">False</label><br>
+++
| +++ <textarea class="notes" name="securityLibraries" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.6 Dependency Patching
| Apply security patches with a severity score of "medium" or higher, or ensure equivalent mitigations are available for all components of the application stack within one month of the patch release
| +++
<input type="radio" id="dependencyPatchingTrue" name="dependencyPatching" value="True" disabled>
<label for="dependencyPatchingTrue">True</label><br>
<input type="radio" id="dependencyPatchingFalse" name="dependencyPatching" value="False" disabled>
<label for="dependencyPatchingFalse">False</label><br>
+++
| +++ <textarea class="notes" name="dependencyPatching" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.7 Logging
| Keep logs of:

  * Users logging in and out
  * Read, write, delete operations on application and system users and objects
  * Security settings changes (including disabling logging)
  * Application owner access to customer data (access transparency)

Logs must include user ID, IP address, valid timestamp, type of action performed, and object of this action.
Logs must be stored for at least 30 days, and should not contain sensitive data or payloads. 
| +++
<input type="radio" id="loggingTrue" name="logging" value="True" disabled>
<label for="loggingTrue">True</label><br>
<input type="radio" id="loggingFalse" name="logging" value="False" disabled>
<label for="loggingFalse">False</label><br>
+++
| +++ <textarea class="notes" name="logging" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.8 Backup and Disaster recovery
| * Securely back up all data to a different location than where the application is running
  * Maintain and periodically test disaster recovery plans
  * Periodically test backup restoration
  | +++
<input type="radio" id="backupAndDisasterRecoveryTrue" name="backupAndDisasterRecovery" value="True" disabled>
<label for="backupAndDisasterRecoveryTrue">True</label><br>
<input type="radio" id="backupAndDisasterRecoveryFalse" name="backupAndDisasterRecovery" value="False" disabled>
<label for="backupAndDisasterRecoveryFalse">False</label><br>
+++
| +++ <textarea class="notes" name="backupAndDisasterRecovery" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 2.9 Encryption
| Use available means of encryption to protect sensitive data in transit between systems and at rest in online data storages and backups
| +++
<input type="radio" id="encryptionTrue" name="encryption" value="True" disabled>
<label for="encryptionTrue">True</label><br>
<input type="radio" id="encryptionFalse" name="encryption" value="False" disabled>
<label for="encryptionFalse">False</label><br>
+++
| +++ <textarea class="notes" name="encryption" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

4+<h| 3 Application implementation controls
h| Control
h| Description
h| Response
h| Notes

| 3.1 List of data
| Maintain a list of sensitive data types that the application is expected to process
| +++
<input type="radio" id="listOfDataTrue" name="listOfData" value="True" disabled>
<label for="listOfDataTrue">True</label><br>
<input type="radio" id="listOfDataFalse" name="listOfData" value="False" disabled>
<label for="listOfDataFalse">False</label><br>
+++
| +++ <textarea class="notes" name="listOfData" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 3.2 Data flow diagram
| Maintain an up-to-date diagram indicating how sensitive data reaches your systems and where it ends up being stored
| +++
<input type="radio" id="dataFlowDiagramTrue" name="dataFlowDiagram" value="True" disabled>
<label for="dataFlowDiagramTrue">True</label><br>
<input type="radio" id="dataFlowDiagramFalse" name="dataFlowDiagram" value="False" disabled>
<label for="dataFlowDiagramFalse">False</label><br>
+++
| +++ <textarea class="notes" name="dataFlowDiagram" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 3.3 Vulnerability prevention
| Train your developers and implement development guidelines to prevent at least the following vulnerabilities:

  * Authorization bypass. Example: Accessing other customers' data or admin features from a regular account
  * Insecure session ID. Examples: Guessable token; a token stored in an insecure location (e.g. cookie without secure and httpOnly flags set)
  * Injections. Examples: SQL injection, NoSQL injection, XXE, OS command injection
  * Cross-site scripting. Examples: Calling insecure JavaScript functions, performing insecure DOM manipulations, echoing back user input into HTML without escaping
  * Cross-site request forgery. Example: Accepting requests with an Origin header from a different domain
  * Use of vulnerable libraries. Example: Using server-side frameworks or JavaScript libraries with known vulnerabilities
| +++
<input type="radio" id="vulnerabilityPreventionTrue" name="vulnerabilityPrevention" value="True" disabled>
<label for="vulnerabilityPreventionTrue">True</label><br>
<input type="radio" id="vulnerabilityPreventionFalse" name="vulnerabilityPrevention" value="False" disabled>
<label for="vulnerabilityPreventionFalse">False</label><br>
+++
| +++ <textarea class="notes" name="vulnerabilityPrevention" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 3.4 Time to fix vulnerabilities
| Produce and deploy patches to address application vulnerabilities that materially impact security within 90 days of discovery.
| +++
<input type="radio" id="timeToFixTrue" name="timeToFix" value="True" disabled>
<label for="timeToFixTrue">True</label><br>
<input type="radio" id="timeToFixFalse" name="timeToFix" value="False" disabled>
<label for="timeToFixFalse">False</label><br>
+++
| +++ <textarea class="notes" name="timeToFix" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

4+<h| 4 Operational controls
h| Control
h| Description
h| Response
h| Notes

| 4.1 Physical access
| Validate the physical security of relevant facilities by ensuring the following controls are in place:

  * Layered perimeter controls and interior barriers
  * Managed access to keys
  * Entry and exit logs
  * Appropriate response plan for intruder alerts
| +++
<input type="radio" id="physicalTrue" name="physical" value="True" disabled>
<label for="physicalTrue">True</label><br>
<input type="radio" id="physicalFalse" name="physical" value="False" disabled>
<label for="physicalFalse">False</label><br>
+++
| +++ <textarea class="notes" name="physical" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

| 4.2 Logical access
| * Limit sensitive data access exclusively to users with a legitimate need. The data owner must authorize such access
  * Deactivate redundant accounts and expired access grants in a timely manner
  * Perform regular reviews of access to validate need to know
| +++
<input type="radio" id="logicalTrue" name="logical" value="True" disabled>
<label for="logicalTrue">True</label><br>
<input type="radio" id="logicalFalse" name="logical" value="False" disabled>
<label for="logicalFalse">False</label><br>
+++
| +++ <textarea class="notes" name="logical" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++
  
| 4.3 Subprocessors
| * Publish a list of third-party companies with access to customer data on your website
  * Assess third-party companies annually against this baseline
| +++
<input type="radio" id="subprocessorsTrue" name="subprocessors" value="True" disabled>
<label for="subprocessorsTrue">True</label><br>
<input type="radio" id="subprocessorsFalse" name="subprocessors" value="False" disabled>
<label for="subprocessorsFalse">False</label><br>
+++
| +++ <textarea class="notes" name="subprocessors" onkeydown="dynamicHeight(event)" rows="4" cols="25" disabled> +++

|===

== License

This document is public domain under https://creativecommons.org/publicdomain/zero/1.0/[CC0 1.0 Universal] license.

++++
<script>
let dataObj = [];
let url = window.location.href;

function toPrintTheChecklist(event) {
  dataGenaration();
  let errorEle = document.getElementsByClassName('error');
  if(errorEle.length === 0 && dataObj.length !== 0) {
    window.print();
  }else {
    let errorMessageElement = '<div class="error">Please fill All the response</div>';
    toAddErrorMessage(event.target.parentElement, errorMessageElement);
  }
}
function dynamicHeight(event){
  if(String(event.target.scrollHeight) > event.target.style.height){
    event.target.style.height = (event.target.scrollHeight + 10)+"px";
  }
}
function onlineChecklist() {
  let inputEle = document.getElementsByTagName('input');
  let textareaEle = document.getElementsByTagName('textarea');
  if (dataObj.length === 0){
    for (let i=0; i< inputEle.length; i++){
      inputEle[i].disabled = false;
      if (textareaEle[i] !== undefined) {
        textareaEle[i].disabled = false;

        let inputObj = {
          inputName: '',
          response: '',
          notes: ''
        };
        inputObj.inputName = textareaEle[i].name;
        dataObj.push(inputObj);
      }
    }
  }
  
}
function dataGenaration() {
  for (let i=0; i< dataObj.length; i++){
    let name = dataObj[i].inputName;
    let checkedEle = document.querySelector('input[name="'+name+'"]:checked');
    let textareaEle = document.querySelector('textarea[name="'+name+'"]');

    if (textareaEle.value.trim() !== '') {
      dataObj[i].notes = textareaEle.value;
      toRemoveErrorMessage(textareaEle);
    }
    else if (i < 2){
      let errorMessageElement = '<div class="error">Please fill the '+name+' Name.</div>';
      toAddErrorMessage(textareaEle, errorMessageElement);
    }
    if (checkedEle !== null && checkedEle.value !== null) {
      dataObj[i].response = checkedEle.value;

      toRemoveErrorMessage(checkedEle);      
      // To check the response is given in the checklist.
    } else if (i > 1 && checkedEle === null){
      let checklistParentEle =  document.querySelector('input[name="'+name+'"]').parentElement;
      let errorMessageElement = '<div class="error">Please fill your response</div>';

      toAddErrorMessage(checklistParentEle, errorMessageElement);
    }
  }
}
function toAddErrorMessage (inputElement, errorMessageElement) {
  if (inputElement.parentElement.getElementsByClassName('error').length === 0) {
    inputElement.insertAdjacentHTML('afterend', errorMessageElement);
  }
}
function toRemoveErrorMessage (inputElement) {
  let errorEle = inputElement.parentElement.getElementsByClassName('error');
  if(errorEle.length !== 0){
    errorEle[0].remove();
  }
}
function generateIframe(event) {
  dataGenaration();
  let errorEle = document.getElementsByClassName('error');
  
  if(errorEle.length === 0 && dataObj.length !== 0) {
    let dataString = JSON.stringify(dataObj);
    let encodeURL = url + "?data=" +encodeURIComponent(dataString)+"";
    generatedLinkEle = document.getElementsByClassName('generatedLink');
    generatedLinkEle[0].style.display = 'block';
    generatedLinkEle[0].href = encodeURL;
    toRemoveErrorMessage(event.target.parentElement)
  }else {
    let errorMessageElement = '<div class="error">Please fill All the response</div>';
    toAddErrorMessage(event.target.parentElement, errorMessageElement)
  }
}
(function() {
  let data = window.location.search;
  if( data !== ''){
    let urlParam = new URLSearchParams(window.location.search);
    data = urlParam.get('data');
    dataObj = JSON.parse(data);

    for (let i=0; i< dataObj.length; i++){
      let name = dataObj[i].inputName;
      let checkedEle = document.querySelectorAll('input[name="'+name+'"]');
      let textareaEle = document.querySelector('textarea[name="'+name+'"]');

      if (textareaEle.length !== 0) {
        textareaEle.value = dataObj[i].notes ;
      }
      if (checkedEle.length !== 0 ) {
        if ((dataObj[i].response).toLowerCase() === "true") {
          checkedEle[0].checked = dataObj[i].response.toLowerCase();
          checkedEle[0].parentElement.parentElement.style.background = "lightgreen"
        } else if((dataObj[i].response).toLowerCase() === "false") {
          checkedEle[1].checked = dataObj[i].response.toLowerCase();
          checkedEle[0].parentElement.parentElement.style.background = "orangered"
        }
      }
    }
    let actionBtn = document.querySelectorAll('button');
    for(let i=0;i<actionBtn.length; i++){
      actionBtn[i].disabled = true;
      actionBtn[i].style.cursor = "not-allowed";
    }

  }
})();
</script>
++++