version: 0.2

phases:
  install:
    commands:
      - npm install --silent -g pnpm@7.0.1
      - pnpm install --frozen-lockfile --prod
  build:
    commands:
      - pnpm run build
      - cd dist
      - OLDNAME=`ls -1 index.*.css` NEWNAME="index.`sha256sum $OLDNAME | cut -c57-64`.css"
      - 'echo "was: $OLDNAME; now: $NEWNAME"'
      - find . -name "*.html" -exec sed -i "s/$OLDNAME/$NEWNAME/" {} +
      - mv $OLDNAME $NEWNAME
      - mkdir assets
      - find . -maxdepth 1 -type f -not -name '*.html' -print0 | xargs -0 -I {} mv {} assets/

artifacts:
  files:
    - '**.*'
  secondary-artifacts:
    ImmutableAssets:
      files:
        - '**/*'
      base-directory: 'dist/assets'
      name: ImmutableAssets
    NotCachedAssets:
      files:
        - '**/*.html'
        - '**/site.webmanifest'
      base-directory: 'dist'
      name: NotCachedAssets
